name = "Giffndof"
uuid = "eaf921fd-e117-45b5-a8aa-9e03c9269769"
authors = ["Eduardo Lenz Cardoso", "Matheus Janczkowski Fogaça"]
version = "1.0.0-DEV"

[deps]
ExponentialAction = "e24c0720-ea99-47e8-929e-571b494574d3"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
